export interface MacroDroidEntry {
    apiKey: string
    householdName: string
}

export function generateMacroDroidFile(configs: MacroDroidEntry[], webhookUrl: string): string {
    const id = () => -(Math.floor(Math.random() * Number.MAX_SAFE_INTEGER) + 1)
    const now = Date.now()
    const makeHttpAction = (apiKey: string) => ({
        disableLogging: false,
        m_classType: 'HttpRequestAction',
        m_constraintList: [],
        m_isDisabled: false,
        m_isOrCondition: false,
        m_SIGUID: id(),
        requestConfig: {
            allFilesAccessPath: '',
            allowAnyCertificate: false,
            basicAuthEnabled: false,
            basicAuthPassword: '',
            basicAuthUsername: '',
            blockNextAction: false,
            clientCertEnabled: false,
            clientCertKeyStoreDisplayName: '',
            clientCertKeyStoreUri: '',
            clientCertPassword: '',
            contentBodyDynamicFileName: '',
            contentBodyFileDisplayName: '',
            contentBodyFileUri: '',
            contentBodyFolderDisplayName: '',
            contentBodyFolderUri: '',
            contentBodySource: 0,
            contentBodyText: `{"title":"{not_title}","body":"{notification}","apiKey":"${apiKey}"}`,
            contentType: 'application/json',
            followRedirects: true,
            headerParams: [],
            localFileUri: '',
            prettifyJson: false,
            queryParams: [],
            requestTimeOutSeconds: 30,
            requestType: 1,
            saveResponseAllFilesAccessPath: '',
            saveResponseFileName: '',
            saveResponseFolderPathDisplayName: '',
            saveResponseFolderPathUri: '',
            saveResponseType: 0,
            saveResponseUseAllFilesAccess: false,
            saveReturnCodeToVariable: false,
            saveReturnHeadersToVariable: false,
            urlToOpen: webhookUrl,
            useAllFilesAccess: false,
            useLocalFileUri: false,
            useStaticContentBodyFile: true,
        },
    })
    const names = configs.map(c => c.householdName).join(', ')
    return JSON.stringify({
        exportFormat: 2,
        exportAppVersion: 596300015,
        timestamp: now,
        variables: [],
        cellTowerGroups: [],
        stopWatches: [],
        userIcons: [],
        customDrawerConfigs: [],
        macroList: [{
            aiGenerated: 0,
            breakpoints: [],
            disabledTimestamp: 0,
            exportedActionBlocks: [],
            forceEvenIfNotEnabledTimestamp: 0,
            isActionBlock: false,
            isExtra: false,
            isFavourite: false,
            lastEditedTimestamp: now,
            localVariables: [],
            localVarsAlphabetical: true,
            m_GUID: id(),
            m_category: 'Uncategorized',
            m_constraintList: [],
            m_description: '',
            m_descriptionOpen: false,
            m_enabled: true,
            m_excludeLog: false,
            m_headingColor: 0,
            m_isOrCondition: false,
            m_name: `Google Wallet → HomeFine (${names})`,
            m_triggerList: [{
                disableLogging: false,
                enableRegex: false,
                ignoreCase: true,
                m_applicationNameList: ['Google Wallet'],
                m_classType: 'NotificationTrigger',
                m_constraintList: [],
                m_exactMatch: false,
                m_excludeApps: false,
                m_excludes: false,
                m_ignoreOngoing: false,
                m_isDisabled: false,
                m_isOrCondition: false,
                m_option: 0,
                m_packageNameList: ['com.google.android.apps.walletnfcrel'],
                m_SIGUID: id(),
                m_soundOption: 0,
                m_supressMultiples: true,
                m_textContent: '',
                matchOptionMessage: 0,
                matchOptionTitle: 0,
                separateTitleAndMessage: false,
            }],
            m_actionList: configs.map(c => makeHttpAction(c.apiKey)),
        }],
    })
}
